// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetRelay.Server.Data;

#nullable disable

namespace NetRelay.Server.Data.Migrations
{
    [DbContext(typeof(NetRelayDbContext))]
    [Migration("20260616023500_AddReleasePackageDeletedAt")]
    partial class AddReleasePackageDeletedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NetRelay.Server.Data.ActivationReceipt", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("InstallationId")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("installation_id");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("issued_at");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("key_id");

                    b.Property<byte[]>("ReceiptId")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("receipt_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("ReceiptId")
                        .IsUnique();

                    b.ToTable("activation_receipts", (string)null);
                });

            modelBuilder.Entity("NetRelay.Server.Data.AdminAccount", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int")
                        .HasColumnName("failed_login_count");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("ProtectedTotpSecret")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("protected_totp_secret");

                    b.Property<byte>("SingletonKey")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("singleton_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("SingletonKey")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("admin_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_admin_accounts_singleton", "`singleton_key` = 1");
                        });
                });

            modelBuilder.Entity("NetRelay.Server.Data.AdminLoginChallengeRecord", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("id");

                    b.Property<byte[]>("AdminAccountId")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("admin_account_id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.HasKey("Id");

                    b.HasIndex("AdminAccountId");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("admin_login_challenges", (string)null);
                });

            modelBuilder.Entity("NetRelay.Server.Data.AdminSession", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("id");

                    b.Property<byte[]>("AdminAccountId")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("admin_account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CsrfTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("csrf_token_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset>("ReauthenticatedUntil")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reauthenticated_until");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SessionTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("session_token_hash")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("AdminAccountId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("SessionTokenHash")
                        .IsUnique();

                    b.ToTable("admin_sessions", (string)null);
                });

            modelBuilder.Entity("NetRelay.Server.Data.Announcement", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayTrigger")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("display_trigger");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("TargetVersionMax")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("target_version_max");

                    b.Property<string>("TargetVersionMin")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("target_version_min");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("Status");

                    b.ToTable("announcements", (string)null);
                });

            modelBuilder.Entity("NetRelay.Server.Data.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("action");

                    b.Property<byte[]>("AdminAccountId")
                        .HasColumnType("binary(16)")
                        .HasColumnName("admin_account_id");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("longtext")
                        .HasColumnName("details_json");

                    b.Property<string>("EntryHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("entry_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PreviousHash")
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("previous_hash")
                        .IsFixedLength();

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("request_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("result");

                    b.Property<string>("TargetId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("Action", "OccurredAt");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("NetRelay.Server.Data.Device", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("id");

                    b.Property<string>("DeviceIdHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("device_id_hash");

                    b.Property<int>("FingerprintVersion")
                        .HasColumnType("int")
                        .HasColumnName("fingerprint_version");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("machine_code");

                    b.HasKey("Id");

                    b.HasIndex("DeviceIdHash");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("MachineCode")
                        .IsUnique();

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("NetRelay.Server.Data.DeviceBlock", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("DeviceId")
                        .HasColumnType("binary(16)")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("InstallationId")
                        .HasColumnType("binary(16)")
                        .HasColumnName("installation_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("InstallationId");

                    b.HasIndex("Status");

                    b.ToTable("device_blocks", (string)null);
                });

            modelBuilder.Entity("NetRelay.Server.Data.DeviceEvidence", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("category");

                    b.Property<byte[]>("DeviceId")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("device_id");

                    b.Property<string>("EvidenceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("evidence_hash");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_seen_at");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Category", "EvidenceHash")
                        .IsUnique();

                    b.ToTable("device_evidence", (string)null);
                });

            modelBuilder.Entity("NetRelay.Server.Data.DeviceInstallation", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("id");

                    b.Property<string>("ClientVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("client_version");

                    b.Property<byte[]>("DeviceId")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("first_seen_at");

                    b.Property<byte[]>("InstallationId")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("installation_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("OsVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("os_version");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("int")
                        .HasColumnName("protocol_version");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId")
                        .IsUnique();

                    b.HasIndex("DeviceId", "LastSeenAt");

                    b.ToTable("device_installations", (string)null);
                });

            modelBuilder.Entity("NetRelay.Server.Data.Feedback", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("id");

                    b.Property<string>("AttachmentFilename")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("attachment_filename");

                    b.Property<long?>("AttachmentSize")
                        .HasColumnType("bigint")
                        .HasColumnName("attachment_size");

                    b.Property<string>("ClientVersion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("client_version");

                    b.Property<string>("Contact")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("contact");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceIdHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("device_id_hash");

                    b.Property<bool>("HasAttachment")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_attachment");

                    b.Property<byte[]>("InstallationId")
                        .HasColumnType("binary(16)")
                        .HasColumnName("installation_id");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("os_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("StatusUpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("status_updated_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("feedbacks", (string)null);
                });

            modelBuilder.Entity("NetRelay.Server.Data.GlobalPolicy", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("id");

                    b.Property<bool>("AllowUpdate")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("allow_update");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("TargetVersionMax")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("target_version_max");

                    b.Property<string>("TargetVersionMin")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("target_version_min");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("global_policies", (string)null);
                });

            modelBuilder.Entity("NetRelay.Server.Data.Release", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("id");

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("architecture");

                    b.Property<string>("AssetPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("asset_path");

                    b.Property<string>("Changelog")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("changelog");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_mandatory");

                    b.Property<string>("MinUpgradableVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("min_upgradable_version");

                    b.Property<long>("PackageSize")
                        .HasColumnType("bigint")
                        .HasColumnName("package_size");

                    b.Property<DateTimeOffset?>("PackageDeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("package_deleted_at");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset>("ReleaseDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("release_date");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("sha256")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("Version", "Channel", "Architecture")
                        .IsUnique();

                    b.ToTable("releases", (string)null);
                });

            modelBuilder.Entity("NetRelay.Server.Data.AdminLoginChallengeRecord", b =>
                {
                    b.HasOne("NetRelay.Server.Data.AdminAccount", null)
                        .WithMany()
                        .HasForeignKey("AdminAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NetRelay.Server.Data.AdminSession", b =>
                {
                    b.HasOne("NetRelay.Server.Data.AdminAccount", "AdminAccount")
                        .WithMany()
                        .HasForeignKey("AdminAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminAccount");
                });

            modelBuilder.Entity("NetRelay.Server.Data.DeviceBlock", b =>
                {
                    b.HasOne("NetRelay.Server.Data.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NetRelay.Server.Data.DeviceInstallation", "DeviceInstallation")
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Device");

                    b.Navigation("DeviceInstallation");
                });

            modelBuilder.Entity("NetRelay.Server.Data.DeviceEvidence", b =>
                {
                    b.HasOne("NetRelay.Server.Data.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("NetRelay.Server.Data.DeviceInstallation", b =>
                {
                    b.HasOne("NetRelay.Server.Data.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });
#pragma warning restore 612, 618
        }
    }
}
