// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetRelay.Server.Data;

#nullable disable

namespace NetRelay.Server.Data.Migrations
{
    [DbContext(typeof(NetRelayDbContext))]
    [Migration("20260613082750_InitialAdminFoundation")]
    partial class InitialAdminFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NetRelay.Server.Data.AdminAccount", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int")
                        .HasColumnName("failed_login_count");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("ProtectedTotpSecret")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("protected_totp_secret");

                    b.Property<byte>("SingletonKey")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("singleton_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("SingletonKey")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("admin_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_admin_accounts_singleton", "`singleton_key` = 1");
                        });
                });

            modelBuilder.Entity("NetRelay.Server.Data.AdminLoginChallengeRecord", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("id");

                    b.Property<byte[]>("AdminAccountId")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("admin_account_id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.HasKey("Id");

                    b.HasIndex("AdminAccountId");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("admin_login_challenges", (string)null);
                });

            modelBuilder.Entity("NetRelay.Server.Data.AdminSession", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("id");

                    b.Property<byte[]>("AdminAccountId")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .HasColumnName("admin_account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CsrfTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("csrf_token_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset>("ReauthenticatedUntil")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reauthenticated_until");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SessionTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("session_token_hash")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("AdminAccountId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("SessionTokenHash")
                        .IsUnique();

                    b.ToTable("admin_sessions", (string)null);
                });

            modelBuilder.Entity("NetRelay.Server.Data.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("action");

                    b.Property<byte[]>("AdminAccountId")
                        .HasColumnType("binary(16)")
                        .HasColumnName("admin_account_id");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("longtext")
                        .HasColumnName("details_json");

                    b.Property<string>("EntryHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("entry_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PreviousHash")
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("previous_hash")
                        .IsFixedLength();

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("request_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("result");

                    b.Property<string>("TargetId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("Action", "OccurredAt");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("NetRelay.Server.Data.AdminLoginChallengeRecord", b =>
                {
                    b.HasOne("NetRelay.Server.Data.AdminAccount", null)
                        .WithMany()
                        .HasForeignKey("AdminAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NetRelay.Server.Data.AdminSession", b =>
                {
                    b.HasOne("NetRelay.Server.Data.AdminAccount", "AdminAccount")
                        .WithMany()
                        .HasForeignKey("AdminAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
