<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationIcon>Assets\NetRelay.ico</ApplicationIcon>
    <AssemblyName>NetRelay</AssemblyName>
    <RootNamespace>NetRelay</RootNamespace>
    <Version>1.2.1</Version>
    <AssemblyVersion>1.2.1.0</AssemblyVersion>
    <FileVersion>1.2.1.0</FileVersion>
    <InformationalVersion>1.2.1</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Company>lansi</Company>
    <Authors>lansi</Authors>
    <Product>NetRelay</Product>
    <Platforms>x64</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishSelfContained>true</PublishSelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\NetRelay.ico" />
    <None Include="Assets\NetRelay.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DeviceId" Version="6.11.0" />
    <PackageReference Include="DeviceId.Windows" Version="6.11.0" />
    <PackageReference Include="DeviceId.Windows.Wmi" Version="6.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetRelay.Contracts\NetRelay.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="bootstrap-config.json" />
  </ItemGroup>
</Project>
