<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>NetRelay.Updater</AssemblyName>
    <RootNamespace>NetRelay.Updater</RootNamespace>
    <SelfContained>false</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetRelay.Contracts\NetRelay.Contracts.csproj" />
  </ItemGroup>

</Project>
